name: tests

on:
  push:
    branches: [main, staging, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
